spring:
  shell:
    interactive:
      enabled: true
    history:
      enabled: false
  datasource:
    url: jdbc:h2:mem:work-005-db
    username: sa
    password:
  sql:
    init:
      mode: always
      data-locations: db/data.sql
      schema-locations: db/schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true